import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/hooks/auth/useAuth";
import { OnlineUsersProvider } from "@/context/OnlineUsersContext";
import { UnreadProvider } from "@/context/UnreadContext";
import { Toaster } from "react-hot-toast";
import GlobalNotificationListener from "@/components/globalNotificationListener/GlobalNotificationListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans scroll-smooth`}
      >
        <AuthProvider>
          <OnlineUsersProvider>
            <UnreadProvider>
              <Toaster position="top-right" />
              <GlobalNotificationListener />
              {children}
            </UnreadProvider>
          </OnlineUsersProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
